{% set version = "9.3.2" %}

package:
  name: pytango
  version: {{ version }}

source:
  git_url: https://github.com/tango-cs/pytango.git
  git_tag: v{{ version }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cppzmq
    - cpptango >=9.3,<9.4
    - boost
    - python {{ python }}
    - numpy >=1.1
  run:
    - {{ pin_compatible('cpptango', max_pin='x.x') }}  # Strict pinning
    - {{ pin_compatible('boost', max_pin='x.x') }}  # Strict pinning
    - {{ pin_compatible('numpy', min_pin='x') }}  # Loose pinning
    - {{ pin_compatible('python', max_pin='x.x') }}  # Strict pinning
    - six >=1.10
    - enum34 # [py27]

test:
  requires:
    - pytest
    - pytest-xdist
    - gevent
    - psutil
    - trollius # [py27]
    - tango-test
  source_files:
    - tests/
    - setup.cfg
  imports:
    - PyTango
    - tango
  commands:
    - pytest

about:
  home: http://pytango.rtfd.io
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Python binding for the TANGO control system'
